{"variants":[{"paths":["\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError"]]},"metadata":{"role":"symbol","title":"SignInWithAppleError.invalidCallback","roleHeading":"Case","modules":[{"name":"RxFireAuth"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidCallback","kind":"identifier"}],"externalID":"s:10RxFireAuth20SignInWithAppleErrorO15invalidCallbackyA2CmF","symbolKind":"case"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"A callback has been invoked without a nonce."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCallback","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError":{"url":"\/documentation\/rxfireauth\/signinwithappleerror","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SignInWithAppleError","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SignInWithAppleError"}],"role":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError","abstract":[{"text":"Errors thrown by ","type":"text"},{"code":"SignInWithAppleHandler","type":"codeVoice"},{"text":" instances.","type":"text"}],"title":"SignInWithAppleError"},"doc://RxFireAuth/documentation/RxFireAuth":{"title":"RxFireAuth","url":"\/documentation\/rxfireauth","kind":"symbol","type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","abstract":[],"role":"collection"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidCallback":{"abstract":[{"type":"text","text":"A callback has been invoked without a nonce."}],"role":"symbol","title":"SignInWithAppleError.invalidCallback","type":"topic","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCallback","kind":"identifier"}]}}}