{"abstract":[{"text":"A callback has been invoked without a nonce.","type":"text"}],"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidCallback","kind":"identifier"}],"platforms":["macOS"]}]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback"]}],"metadata":{"externalID":"s:10RxFireAuth20SignInWithAppleErrorO15invalidCallbackyA2CmF","title":"SignInWithAppleError.invalidCallback","role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidCallback","kind":"identifier"}],"modules":[{"name":"RxFireAuth"}]},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError"]]},"references":{"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError":{"abstract":[{"text":"Errors thrown by ","type":"text"},{"type":"codeVoice","code":"SignInWithAppleHandler"},{"text":" instances.","type":"text"}],"title":"SignInWithAppleError","type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError","url":"\/documentation\/rxfireauth\/signinwithappleerror","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SignInWithAppleError","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SignInWithAppleError"}]},"doc://RxFireAuth/documentation/RxFireAuth":{"type":"topic","url":"\/documentation\/rxfireauth","abstract":[],"title":"RxFireAuth","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidCallback":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidCallback"}],"kind":"symbol","type":"topic","abstract":[{"text":"A callback has been invoked without a nonce.","type":"text"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","title":"SignInWithAppleError.invalidCallback","url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback","role":"symbol"}}}