{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError"]]},"variants":[{"paths":["\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidCallback","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"RxFireAuth"}],"roleHeading":"Case","title":"SignInWithAppleError.invalidCallback","externalID":"s:10RxFireAuth20SignInWithAppleErrorO15invalidCallbackyA2CmF","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidCallback","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"A callback has been invoked without a nonce."}],"references":{"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError":{"navigatorTitle":[{"text":"SignInWithAppleError","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/rxfireauth\/signinwithappleerror","title":"SignInWithAppleError","role":"symbol","abstract":[{"type":"text","text":"Errors thrown by "},{"type":"codeVoice","code":"SignInWithAppleHandler"},{"text":" instances.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignInWithAppleError","kind":"identifier"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidCallback":{"type":"topic","kind":"symbol","url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback","title":"SignInWithAppleError.invalidCallback","role":"symbol","abstract":[{"text":"A callback has been invoked without a nonce.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCallback"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback"},"doc://RxFireAuth/documentation/RxFireAuth":{"title":"RxFireAuth","abstract":[],"type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","url":"\/documentation\/rxfireauth"}}}