{"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"abstract":[{"text":"The requested action cannot be performed because there is already an anonymous user logged-in.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/alreadyanonymous"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"alreadyAnonymous"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alreadyAnonymous"}],"role":"symbol","title":"UserError.alreadyAnonymous","symbolKind":"case","roleHeading":"Case","modules":[{"name":"RxFireAuth"}],"externalID":"s:10RxFireAuth9UserErrorO16alreadyAnonymousyA2CmF"},"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/alreadyAnonymous":{"role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alreadyAnonymous"}],"title":"UserError.alreadyAnonymous","url":"\/documentation\/rxfireauth\/usererror\/alreadyanonymous","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","abstract":[{"type":"text","text":"The requested action cannot be performed because there is already an anonymous user logged-in."}],"type":"topic"},"doc://RxFireAuth/documentation/RxFireAuth":{"kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","type":"topic","title":"RxFireAuth","abstract":[],"url":"\/documentation\/rxfireauth","role":"collection"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"title":"UserError","kind":"symbol","abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}],"role":"symbol","url":"\/documentation\/rxfireauth\/usererror","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserError"}],"type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","navigatorTitle":[{"text":"UserError","kind":"identifier"}]}}}