{"abstract":[{"text":"The requested action cannot be performed because there is already an anonymous user logged-in.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alreadyAnonymous","kind":"identifier"}],"modules":[{"name":"RxFireAuth"}],"symbolKind":"case","externalID":"s:10RxFireAuth9UserErrorO16alreadyAnonymousyA2CmF","title":"UserError.alreadyAnonymous","roleHeading":"Case","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/usererror\/alreadyanonymous"]}],"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/alreadyAnonymous":{"kind":"symbol","url":"\/documentation\/rxfireauth\/usererror\/alreadyanonymous","type":"topic","abstract":[{"type":"text","text":"The requested action cannot be performed because there is already an anonymous user logged-in."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alreadyAnonymous"}],"title":"UserError.alreadyAnonymous","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/alreadyAnonymous","role":"symbol"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"role":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","abstract":[{"text":"Errors thrown by  ","type":"text"},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}],"navigatorTitle":[{"text":"UserError","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserError"}],"title":"UserError","type":"topic","url":"\/documentation\/rxfireauth\/usererror"},"doc://RxFireAuth/documentation/RxFireAuth":{"title":"RxFireAuth","url":"\/documentation\/rxfireauth","kind":"symbol","type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","abstract":[],"role":"collection"}}}