{"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidUpdate","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/invalidupdate"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","interfaceLanguage":"swift"},"metadata":{"externalID":"s:10RxFireAuth9UserErrorO13invalidUpdateyA2CmF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidUpdate"}],"role":"symbol","symbolKind":"case","modules":[{"name":"RxFireAuth"}],"title":"UserError.invalidUpdate","roleHeading":"Case"},"abstract":[{"type":"text","text":"The update cannot be performed because of invalid data."}],"sections":[],"kind":"symbol","references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/invalidUpdate":{"url":"\/documentation\/rxfireauth\/usererror\/invalidupdate","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","abstract":[{"text":"The update cannot be performed because of invalid data.","type":"text"}],"title":"UserError.invalidUpdate","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidUpdate","kind":"identifier"}]},"doc://RxFireAuth/documentation/RxFireAuth":{"url":"\/documentation\/rxfireauth","abstract":[],"role":"collection","title":"RxFireAuth","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","type":"topic","kind":"symbol"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserError","kind":"identifier"}],"title":"UserError","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","type":"topic","abstract":[{"text":"Errors thrown by  ","type":"text"},{"code":"UserManagerType","type":"codeVoice"},{"type":"text","text":" implementations."}],"navigatorTitle":[{"kind":"identifier","text":"UserError"}],"role":"symbol","url":"\/documentation\/rxfireauth\/usererror","kind":"symbol"}}}