{"abstract":[{"type":"text","text":"The update cannot be performed because of invalid data."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/usererror\/invalidupdate"]}],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidUpdate","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"metadata":{"symbolKind":"case","roleHeading":"Case","modules":[{"name":"RxFireAuth"}],"role":"symbol","externalID":"s:10RxFireAuth9UserErrorO13invalidUpdateyA2CmF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidUpdate"}],"title":"UserError.invalidUpdate"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate"},"references":{"doc://RxFireAuth/documentation/RxFireAuth":{"type":"topic","url":"\/documentation\/rxfireauth","abstract":[],"title":"RxFireAuth","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"type":"topic","url":"\/documentation\/rxfireauth\/usererror","abstract":[{"text":"Errors thrown by  ","type":"text"},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}],"navigatorTitle":[{"text":"UserError","kind":"identifier"}],"title":"UserError","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserError"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","role":"symbol"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/invalidUpdate":{"title":"UserError.invalidUpdate","url":"\/documentation\/rxfireauth\/usererror\/invalidupdate","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidUpdate"}],"abstract":[{"type":"text","text":"The update cannot be performed because of invalid data."}],"kind":"symbol"}}}