{"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/invalidupdate"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The update cannot be performed because of invalid data.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidUpdate"}]}]}],"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","interfaceLanguage":"swift"},"metadata":{"title":"UserError.invalidUpdate","symbolKind":"case","roleHeading":"Case","role":"symbol","externalID":"s:10RxFireAuth9UserErrorO13invalidUpdateyA2CmF","modules":[{"name":"RxFireAuth"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidUpdate"}]},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/invalidUpdate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidUpdate"}],"type":"topic","abstract":[{"type":"text","text":"The update cannot be performed because of invalid data."}],"title":"UserError.invalidUpdate","url":"\/documentation\/rxfireauth\/usererror\/invalidupdate","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","role":"symbol"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserError"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserError"}],"url":"\/documentation\/rxfireauth\/usererror","title":"UserError","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"},"doc://RxFireAuth/documentation/RxFireAuth":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","url":"\/documentation\/rxfireauth","type":"topic","title":"RxFireAuth"}}}