{"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate"},"metadata":{"symbolKind":"case","roleHeading":"Case","modules":[{"name":"RxFireAuth"}],"externalID":"s:10RxFireAuth9UserErrorO13invalidUpdateyA2CmF","title":"UserError.invalidUpdate","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidUpdate","kind":"identifier"}],"role":"symbol"},"abstract":[{"text":"The update cannot be performed because of invalid data.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidUpdate","kind":"identifier"}],"languages":["swift"],"platforms":["macOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/invalidupdate"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://RxFireAuth/documentation/RxFireAuth":{"url":"\/documentation\/rxfireauth","abstract":[],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","kind":"symbol","title":"RxFireAuth","type":"topic"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"abstract":[{"text":"Errors thrown by  ","type":"text"},{"code":"UserManagerType","type":"codeVoice"},{"type":"text","text":" implementations."}],"url":"\/documentation\/rxfireauth\/usererror","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UserError","kind":"identifier"}],"role":"symbol","title":"UserError","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","navigatorTitle":[{"text":"UserError","kind":"identifier"}]},"doc://RxFireAuth/documentation/RxFireAuth/UserError/invalidUpdate":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidUpdate","kind":"identifier"}],"role":"symbol","title":"UserError.invalidUpdate","type":"topic","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","abstract":[{"type":"text","text":"The update cannot be performed because of invalid data."}],"url":"\/documentation\/rxfireauth\/usererror\/invalidupdate"}}}