{"kind":"symbol","abstract":[{"text":"The update cannot be performed because of invalid data.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/invalidupdate"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"case","externalID":"s:10RxFireAuth9UserErrorO13invalidUpdateyA2CmF","roleHeading":"Case","title":"UserError.invalidUpdate","role":"symbol","modules":[{"name":"RxFireAuth"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidUpdate"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidUpdate"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"type":"text","text":" implementations."}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","navigatorTitle":[{"text":"UserError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"UserError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/rxfireauth\/usererror","title":"UserError"},"doc://RxFireAuth/documentation/RxFireAuth":{"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","type":"topic","kind":"symbol","title":"RxFireAuth","abstract":[],"url":"\/documentation\/rxfireauth"},"doc://RxFireAuth/documentation/RxFireAuth/UserError/invalidUpdate":{"type":"topic","title":"UserError.invalidUpdate","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","abstract":[{"type":"text","text":"The update cannot be performed because of invalid data."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidUpdate"}],"url":"\/documentation\/rxfireauth\/usererror\/invalidupdate"}}}