{"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The update cannot be performed because of invalid data."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/usererror\/invalidupdate"]}],"metadata":{"symbolKind":"case","externalID":"s:10RxFireAuth9UserErrorO13invalidUpdateyA2CmF","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidUpdate"}],"roleHeading":"Case","modules":[{"name":"RxFireAuth"}],"title":"UserError.invalidUpdate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidUpdate","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://RxFireAuth/documentation/RxFireAuth":{"abstract":[],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","title":"RxFireAuth","url":"\/documentation\/rxfireauth"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"kind":"symbol","url":"\/documentation\/rxfireauth\/usererror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserError","kind":"identifier"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","title":"UserError","role":"symbol","type":"topic","navigatorTitle":[{"text":"UserError","kind":"identifier"}],"abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}]},"doc://RxFireAuth/documentation/RxFireAuth/UserError/invalidUpdate":{"title":"UserError.invalidUpdate","kind":"symbol","url":"\/documentation\/rxfireauth\/usererror\/invalidupdate","role":"symbol","abstract":[{"type":"text","text":"The update cannot be performed because of invalid data."}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/invalidUpdate","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"invalidUpdate","kind":"identifier"}]}}}