{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkError"}],"title":"UserError.networkError","symbolKind":"case","modules":[{"name":"RxFireAuth"}],"role":"symbol","roleHeading":"Case","externalID":"s:10RxFireAuth9UserErrorO07networkE0yA2CmF"},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/networkError"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"An error occurred while reaching Firebase servers.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/rxfireauth\/usererror\/networkerror"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://RxFireAuth/documentation/RxFireAuth":{"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","kind":"symbol","role":"collection","abstract":[],"url":"\/documentation\/rxfireauth","title":"RxFireAuth","type":"topic"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"url":"\/documentation\/rxfireauth\/usererror","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","abstract":[{"text":"Errors thrown by  ","type":"text"},{"code":"UserManagerType","type":"codeVoice"},{"type":"text","text":" implementations."}],"title":"UserError","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserError"}],"navigatorTitle":[{"kind":"identifier","text":"UserError"}]},"doc://RxFireAuth/documentation/RxFireAuth/UserError/networkError":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkError"}],"title":"UserError.networkError","type":"topic","url":"\/documentation\/rxfireauth\/usererror\/networkerror","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"An error occurred while reaching Firebase servers."}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/networkError"}}}