{"kind":"symbol","abstract":[{"type":"text","text":"An error occurred while reaching Firebase servers."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/networkError"},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"sections":[],"metadata":{"role":"symbol","symbolKind":"case","title":"UserError.networkError","roleHeading":"Case","externalID":"s:10RxFireAuth9UserErrorO07networkE0yA2CmF","modules":[{"name":"RxFireAuth"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"networkError","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"networkError","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/usererror\/networkerror"]}],"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/networkError":{"url":"\/documentation\/rxfireauth\/usererror\/networkerror","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/networkError","abstract":[{"text":"An error occurred while reaching Firebase servers.","type":"text"}],"title":"UserError.networkError","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"networkError"}]},"doc://RxFireAuth/documentation/RxFireAuth":{"url":"\/documentation\/rxfireauth","abstract":[],"role":"collection","title":"RxFireAuth","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","type":"topic","kind":"symbol"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserError","kind":"identifier"}],"title":"UserError","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","type":"topic","abstract":[{"text":"Errors thrown by  ","type":"text"},{"code":"UserManagerType","type":"codeVoice"},{"type":"text","text":" implementations."}],"navigatorTitle":[{"kind":"identifier","text":"UserError"}],"role":"symbol","url":"\/documentation\/rxfireauth\/usererror","kind":"symbol"}}}