{"sections":[],"metadata":{"title":"UserError.networkError","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}],"symbolKind":"case","modules":[{"name":"RxFireAuth"}],"externalID":"s:10RxFireAuth9UserErrorO07networkE0yA2CmF","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/networkError"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"networkError","kind":"identifier"}],"platforms":["macOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/usererror\/networkerror"]}],"abstract":[{"type":"text","text":"An error occurred while reaching Firebase servers."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://RxFireAuth/documentation/RxFireAuth/UserError/networkError":{"title":"UserError.networkError","kind":"symbol","url":"\/documentation\/rxfireauth\/usererror\/networkerror","role":"symbol","abstract":[{"text":"An error occurred while reaching Firebase servers.","type":"text"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError\/networkError","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"networkError"}]},"doc://RxFireAuth/documentation/RxFireAuth":{"abstract":[],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","title":"RxFireAuth","url":"\/documentation\/rxfireauth"},"doc://RxFireAuth/documentation/RxFireAuth/UserError":{"kind":"symbol","url":"\/documentation\/rxfireauth\/usererror","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserError","kind":"identifier"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/UserError","title":"UserError","role":"symbol","type":"topic","navigatorTitle":[{"text":"UserError","kind":"identifier"}],"abstract":[{"type":"text","text":"Errors thrown by  "},{"type":"codeVoice","code":"UserManagerType"},{"text":" implementations.","type":"text"}]}}}