{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignInWithAppleError","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/rxfireauth\/signinwithappleerror"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"Errors thrown by ","type":"text"},{"type":"codeVoice","code":"SignInWithAppleHandler"},{"type":"text","text":" instances."}],"identifier":{"url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth"]]},"metadata":{"modules":[{"name":"RxFireAuth"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignInWithAppleError","kind":"identifier"}],"navigatorTitle":[{"text":"SignInWithAppleError","kind":"identifier"}],"title":"SignInWithAppleError","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:10RxFireAuth20SignInWithAppleErrorO"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidIdToken"]},{"identifiers":["doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Equatable-Implementations","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Error-Implementations"],"generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/RxFireAuth\/SQ","doc:\/\/RxFireAuth\/s5ErrorP","doc:\/\/RxFireAuth\/SH","doc:\/\/RxFireAuth\/s8SendableP"],"title":"Conforms To"}],"references":{"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError":{"navigatorTitle":[{"kind":"identifier","text":"SignInWithAppleError"}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignInWithAppleError"}],"abstract":[{"type":"text","text":"Errors thrown by "},{"code":"SignInWithAppleHandler","type":"codeVoice"},{"text":" instances.","type":"text"}],"type":"topic","title":"SignInWithAppleError","url":"\/documentation\/rxfireauth\/signinwithappleerror","kind":"symbol","role":"symbol"},"doc://RxFireAuth/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/RxFireAuth\/s8SendableP"},"doc://RxFireAuth/s5ErrorP":{"title":"Swift.Error","type":"unresolvable","identifier":"doc:\/\/RxFireAuth\/s5ErrorP"},"doc://RxFireAuth/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/RxFireAuth\/SH"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/Error-Implementations":{"title":"Error Implementations","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Error-Implementations","url":"\/documentation\/rxfireauth\/signinwithappleerror\/error-implementations","type":"topic","kind":"article","abstract":[],"role":"collectionGroup"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidIdToken":{"url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalididtoken","role":"symbol","kind":"symbol","type":"topic","abstract":[{"text":"Apple returned an invalid ID token.","type":"text"}],"title":"SignInWithAppleError.invalidIdToken","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidIdToken","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidIdToken","kind":"identifier"}]},"doc://RxFireAuth/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/RxFireAuth\/SQ"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidCallback":{"role":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCallback","kind":"identifier"}],"abstract":[{"text":"A callback has been invoked without a nonce.","type":"text"}],"title":"SignInWithAppleError.invalidCallback","kind":"symbol"},"doc://RxFireAuth/documentation/RxFireAuth":{"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","role":"collection","type":"topic","kind":"symbol","title":"RxFireAuth","abstract":[],"url":"\/documentation\/rxfireauth"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","kind":"article","url":"\/documentation\/rxfireauth\/signinwithappleerror\/equatable-implementations","type":"topic","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Equatable-Implementations","role":"collectionGroup"}}}