{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SignInWithAppleError","kind":"identifier"}],"platforms":["macOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/RxFireAuth\/documentation\/RxFireAuth"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"externalID":"s:10RxFireAuth20SignInWithAppleErrorO","title":"SignInWithAppleError","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"SignInWithAppleError"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SignInWithAppleError","kind":"identifier"}],"role":"symbol","modules":[{"name":"RxFireAuth"}],"symbolKind":"enum"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidIdToken"]},{"title":"Default Implementations","identifiers":["doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Equatable-Implementations","doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Error-Implementations"],"generated":true}],"abstract":[{"text":"Errors thrown by ","type":"text"},{"type":"codeVoice","code":"SignInWithAppleHandler"},{"text":" instances.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/RxFireAuth\/SQ","doc:\/\/RxFireAuth\/s5ErrorP","doc:\/\/RxFireAuth\/SH","doc:\/\/RxFireAuth\/s8SendableP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/rxfireauth\/signinwithappleerror"]}],"references":{"doc://RxFireAuth/documentation/RxFireAuth":{"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth","kind":"symbol","role":"collection","abstract":[],"url":"\/documentation\/rxfireauth","title":"RxFireAuth","type":"topic"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidCallback":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCallback","kind":"identifier"}],"title":"SignInWithAppleError.invalidCallback","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidCallback","url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalidcallback","abstract":[{"type":"text","text":"A callback has been invoked without a nonce."}]},"doc://RxFireAuth/s5ErrorP":{"type":"unresolvable","identifier":"doc:\/\/RxFireAuth\/s5ErrorP","title":"Swift.Error"},"doc://RxFireAuth/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/RxFireAuth\/SQ"},"doc://RxFireAuth/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/RxFireAuth\/SH"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/invalidIdToken":{"title":"SignInWithAppleError.invalidIdToken","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidIdToken","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/invalidIdToken","abstract":[{"text":"Apple returned an invalid ID token.","type":"text"}],"url":"\/documentation\/rxfireauth\/signinwithappleerror\/invalididtoken","type":"topic"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/Error-Implementations":{"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Error-Implementations","abstract":[],"title":"Error Implementations","type":"topic","url":"\/documentation\/rxfireauth\/signinwithappleerror\/error-implementations","role":"collectionGroup","kind":"article"},"doc://RxFireAuth/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/RxFireAuth\/s8SendableP"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError":{"role":"symbol","navigatorTitle":[{"text":"SignInWithAppleError","kind":"identifier"}],"type":"topic","title":"SignInWithAppleError","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SignInWithAppleError"}],"kind":"symbol","url":"\/documentation\/rxfireauth\/signinwithappleerror","abstract":[{"text":"Errors thrown by ","type":"text"},{"type":"codeVoice","code":"SignInWithAppleHandler"},{"type":"text","text":" instances."}],"identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError"},"doc://RxFireAuth/documentation/RxFireAuth/SignInWithAppleError/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","kind":"article","type":"topic","abstract":[],"url":"\/documentation\/rxfireauth\/signinwithappleerror\/equatable-implementations","identifier":"doc:\/\/RxFireAuth\/documentation\/RxFireAuth\/SignInWithAppleError\/Equatable-Implementations"}}}